### ISSUE TITLE
500 error after app redirection

### ISSUE THREAD

**Issue by crunchycarrot** [Shopify/embedded-app-example#31] opened 2015-08-28 09:03 UTC
I got this message "A static HTML page can contain a simple dependency free script to set the top bar to a 500 server error. This page can be found in 'public/500.html'.

After installing the embedded app. Can anyone help?

**Comment by celsodantas** [comment] 2015-08-31 16:41
Hard to say with so little data. Check your logs for the error.

Closing this as this is not a really bug in the app and too generic.
Feel free to reopen/comment if you have more data that the issue is with the example-app. The Shopify forums is good way to get help from other app devs as well.

**Closed by celsodantas** 2015-08-31 16:41 UTC

**Comment by dbnoble** [comment] 2015-11-04 05:33
@crunchycarrot You probably forgot to run rake db:migrate
